import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import UpdatescoreComponent from "./skillTest/components/UpdatescoreComponent";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ankush Submission",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-white overflow-x-hidden">
        {/* navbar section code for layout of the website */}
        <div className=" update  global-text ">
       
          <nav className="global-text border-b-[1px] ">
            <Navbar />
          </nav>
          </div>
          {/* side bar for the application */}
          <div className="flex ">
            <div className="w-[18%]  max-sm:w-[7%] min-w-[45px] ">
              <Sidebar />
            </div>
            <div className="w-[82%] max-sm:w-[93%] ">
              {children}
            </div>
          </div>
       
      
      </body>
    </html>
  );
}
